# Generated by Django 4.2.4 on 2023-09-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_fashion_remove_review_product_remove_review_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fashion',
        ),
    ]
